accounts/urls.py
from django.conf.urls import url
from .import views

app_name='accounts'


urlpatterns = [
    url(r'^signup/$',views.signup_view,name='signup'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^login/$',views.login_view,name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
]

classroom/urls.py
from django.conf.urls import url
from .import views

app_name='classroom'
urlpatterns = [
    url(r'^discussion/$',views.discussion,name="list"),
    url(r'^create/$',views.post_create,name="post_create"),
    url(r'^(?P<slug>[\w-]+)/$',views.post_details,name="detail"),
    
]

pathshala/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^classroom/',include('classroom.urls')),
    url(r'^$',views.homepage),
    url(r'^accounts/',include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

classroom/models.py
from django.db import models
from django.contrib.auth.models import User

#Post-----------------
class Post(models.Model):
  title=models.CharField(max_length=120)
  slug=models.SlugField()
  body=models.TextField()
  date=models.DateTimeField(auto_now_add=True)
  author=models.ForeignKey(User,default=None)

  def __str__(self):
    return self.title

  def snippet(self):
    return self.body[0:100]


#course---------------------

class Course(models.Model):
  course_name=models.CharField(max_length=50)
  syllabus=models.TextField()
  pass_key=models.CharField(max_length=10)
  date=models.DateTimeField(auto_now_add=True)
  creator=models.ForeignKey(User,default=None)


  def __str__(self):
    return self.course_name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)

    class Meta :
    	model=User
    	fields=(
    		'username',
    		'first_name',
    		'last_name',
    	    'email',
    	    'password1',
    	    'password2'
    	)

    	def save(self,commit=True):
    		user=super(RegistrationForm,self).save(commit=False)
    		user.first_name=cleaned_data('first_name')
    		user.last_name=cleaned_data('last_name')
    		user.email=cleaned_data('email')

    		if commit:
    			user.save()
    		return user
		

classroom/forms.py
from django import forms
from.import models



class CreatePost(forms.ModelForm):
	class Meta: 
		model=models.Post
		fields=[
		  'title',
		   'body',
		   'slug',
		]

		

accounts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from.import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
# signup------------
def signup_view(request):
  if request.method=='POST':
      form = RegistrationForm(request.POST)
      if form.is_valid():
  	    user=form.save()
  	    login(request,user)
  	    return redirect('accounts:profile')
  else:
	  form=RegistrationForm()

  return render(request,'accounts/signup.html',{'form':form})



#login--------------- 

def login_view(request):
  if request.method=='POST':
    form=AuthenticationForm(data=request.POST) 
    if form.is_valid():
      user=form.get_user()
      login(request,user)
      if'next'in request.POST:
        return redirect(request.POST.get('next'))
      else:
        return redirect('accounts:profile')
  else:
    form=AuthenticationForm()
  return render(request,'classroom/discussion.html',{'form':form})

#logout------------------

def logout_view(request):
  if request.method=='POST':
  	logout(request)
  	return redirect('accounts:login')

 

#profile
@login_required
def profile(request):
  user=request.user
  return render(request,'accounts/profile.html',{'user':user})

classroom/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from .import forms 

@login_required
def discussion(request):
   posts=Post.objects.all().order_by('date')
   return render(request,"classroom/discussion.html",{'posts':posts})	


@login_required
def post_details(request,slug):
	post=Post.objects.get(slug=slug)  
	return render(request,"classroom/post_details.html",{'post':post})


@login_required
def post_create(request):
	if request.method=='POST':
	  form=forms.CreatePost(request.POST,request.FILES)
	  if form.is_valid():
	  	instance=form.save(commit=False)
	  	instance.author=request.user
	  	instance.save()
	  	return redirect('classroom:list')
	else:
	  form=forms.CreatePost()
	return render(request,"classroom/post_create.html",{'form':form})

pathshala/views.py
from django.http import HttpResponse
from django.shortcuts import render

def  homepage(request):
	return render(request,'homepage.html')

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
	<title>login</title>
</head>
<body>
	<div class="container">
	<h1>Log in</h1>
	<form class="site-form" action="{% url 'accounts:login'%}" method="post">
	   {% csrf_token %}
	   {{from.as_p}}
	   {{form}}
	   {% if request.GET.next %}
	      <input type="hidden" name="next"value="{{request.GET.next}}">
	    {% endif %}
	   <input type="submit" value="login">
	</form>
	</div>

</body>
</html>

accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html>
<head>
	<title>profile</title>
</head>
<body>
	<nav>
		<ul>
			<li>
				<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
				{% csrf_token %}
                 <button type="submit"> logout </button>
				</form>
			</li>
		</ul>
	</nav>
	<div class="container">
	<h1>profile</h1>
	<p>usernaeme: {{user.username}}</p>
	<p>First name: {{user.first_name}}</p>
	<p>Last name: {{user.last_name}}</p>
	<p>Email: {{user.email}}</p>
	</div>

</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>signup</title>
</head>
<body>
	<div class="container">
	<h1>signup</h1>
	<form class="site-form" action="/accounts/signup/" method="post">
	   {% csrf_token %}
	   {{from.as_p}}
	   {{form}}
	   <input type="submit" value="signup">
	</form>
	</div>

</body>
</html>

classroom/templates/classroom/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Classroom</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 15000px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>Pathshala</h4>
      <ul class="nav nav-pills nav-stacked">
        <li><a href="#section1">Course Syllabus</a></li>
        <li><a href="#section2">Discussion</a></li>
        <li class="active"><a href="#section3">Course Materials</a></li>
        <li><a href="#section3">About</a></li>
        <li><a href="#section4">Travelling</a></li>
      </ul>
    </div>

    <div class="col-sm-5">
      <h4><small>RECENT POSTS</small></h4>
      <hr>
      <h2>I Love Food</h2>
      <h5><span class="glyphicon glyphicon-time"></span> Post by Jane Dane, Sep 27, 2015.</h5>
      <h5><span class="label label-danger">Food</span> <span class="label label-primary">Ipsum</span></h5><br>
      <p>Food is my passion. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <br><br>
      
      <h4><small>RECENT POSTS</small></h4>
      <hr>
      <h2>Officially Blogging</h2>
      <h5><span class="glyphicon glyphicon-time"></span> Post by John Doe, Sep 24, 2015.</h5>
      <h5><span class="label label-success">Lorem</span></h5><br>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <hr>

      <h4>Leave a Comment:</h4>
      <form role="form">
        <div class="form-group">
          <textarea class="form-control" rows="3" required></textarea>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
      <br><br>
      
      <p><span class="badge">2</span> Comments:</p><br>
      
      <div class="row">
        <div class="col-sm-2 text-center">
          <img src="bandmember.jpg" class="img-circle" height="65" width="65" alt="Avatar">
        </div>
        <div class="col-sm-10">
          <h4>Anja <small>Sep 29, 2015, 9:12 PM</small></h4>
          <p>Keep up the GREAT work! I am cheering for you!! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <br>
        </div>
        <div class="col-sm-2 text-center">
          <img src="bird.jpg" class="img-circle" height="65" width="65" alt="Avatar">
        </div>
        <div class="col-sm-10">
          <p><span class="badge">1</span> Comment:</p><br>
          <div class="row">
            <div class="col-sm-2 text-center">
              <img src="bird.jpg" class="img-circle" height="65" width="65" alt="Avatar">
            </div>
            <div class="col-xs-10">
              <h4>Nested Bro <small>Sep 25, 2015, 8:28 PM</small></h4>
              <p>Me too! WOW!</p>
              <br>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid">
  <p>Footer Text</p>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
</body>
</html>

classroom/templates/classroom/discussion.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Discussion</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
  <nav>
    <ul>
      <li>
        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
                 <button type="submit"> logout </button>
        </form>
      </li>
    </ul>
  </nav>
	<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>Pathshala</h4>
      <ul class="nav nav-pills nav-stacked">
        <li><a href="#section1">Home</a></li>
        <li><a href="#section2">Syllabus</a></li>
        <li class="active"><a href="#section3">Discussion</a></li>
        <li><a href="#section3">Assignment</a></li>
        <li><a href="#section3">Course Materials</a></li>
        <li><a href="#section4">About</a></li>
      </ul>
    </div>
	
	<div class="posts">
    <h1>Recent posts</h1>
		{% for post in posts %}
		  <div class="col-sm-5 post">
             <h2>{{post.title}}</h2>
             <p>{{post.snippet}}</p>
             <p>{{post.date}}</p>
             <h2><a href="{% url 'classroom:detail' slug=post.slug %}"<small>read more</small> </a></h2>
		  </div>
		
	</div>
		{% endfor %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

classroom/templates/classroom/post_details.html
<!DOCTYPE html>
<html>
<head>
	<title>post_detalis</title>
</head>
<body>
	<div class=="post-detail">
		<img src="{{post.thumb.url}}"/>
		<div class="post">
			<h2>{{post.title}}</h2>
			<P>{{post.body}}</P>
			<p>{{post.date}}</p>
			<p>posted by: {{post.author.username}}</p>
		</div>
	</div>

</body>
</html>

templates/homepage.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>homepage</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<style>
	body{
		background-image: url("{% static "auditorium.jpg" %}");
		background-repeat: no-repeat;
		background-size: cover;
		color: #001a4d;
		font-weight: 4em;

	}
	.jmb{
		width: 400px;
		margin:20%;
		margin-left: 500px;

	}
</style>
 	
 	<div class="jmb">
  <h1 class="display-4 text-center">Pathshala</h1>
  <p class="lead text-center">Anybody can learn or teach</p>
  <p class="lead text-center">
    <a class="btn btn-primary btn-lg" href="/accounts/login" role="button" style=" margin: auto;">Learn more</a>
  </p>
</div>
	

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

</html>